name: editeval
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - libstdcxx-ng>=14.1.0
  - libgcc-ng>=14.1.0
  - pip
  - pytorch=2.3.0=*cuda12.1*
  - cudatoolkit=12.1*
  - ipython
  - ipykernel
  - ipywidgets
  - h5py
  - jupyter_client
  - numpy
  - matplotlib-inline
  - pandas
  - pillow
  - plotly
  - scikit-learn
  - seaborn
  - pip:
      - python-dotenv
      - accelerate
      - datasets
      - matplotlib
      - tqdm
      - transformers
      - jaxtyping
      - einops
      - pytest
      - typeguard
      - fancy_einsum
      - imgkit
      - mistral-common
      - bitsandbytes --index-url=https://pypi.org/simple
      - openai
      - tiktoken