name: rate
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip
  - pytorch=2.3.0=*cuda12.1*
  - ipython
  - ipykernel
  - ipywidgets
  - jupyter_client
  - numpy
  - matplotlib-inline
  - pandas
  - scikit-learn
  - seaborn
  - pip:
      - python-dotenv
      - accelerate== 0.30.1
      - datasets==2.19.1
      - matplotlib
      - tqdm
      - transformers==4.40.2
      - pytest
      - openai==1.51.2